os:
  - linux
  - osx
dist: trusty
sudo: false
language: c
compiler:
- clang
- gcc
script:
- mkdir build && pushd build
- cmake .. -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR -DCMAKE_BUILD_TYPE=Release
- make && make test && make install
- popd && rm -rf build
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -e $TRAVIS_BUILD_DIR/lib/libalmosthere.so; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -e $TRAVIS_BUILD_DIR/lib/libalmosthere_static.a; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -e $TRAVIS_BUILD_DIR/lib/libalmosthere.dylib; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -e $TRAVIS_BUILD_DIR/lib/libalmosthere_static.a; fi
after_success:
- mkdir dist && pushd dist && cmake .. -DCMAKE_BUILD_TYPE=Release && popd
- mv dist almosthere-`cat VERSION`
- tar czf almosthere-`cat VERSION`.tar.gz almosthere-`cat VERSION`
- rm -rf dist
notifications:
  email:
    recipients:
      - danilo.horta@gmail.com
    on_success: never
    on_failure: always
