language: c
jobs:
  include:
    - os: linux
      env: GENERATOR="Unix Makefiles"
    - os: osx
      env: GENERATOR="Unix Makefiles"
    - os: windows
      env: GENERATOR="Visual Studio 15 2017 Win64"
    - os: windows
      env: GENERATOR=Ninja
      before_install:
        - choco install ninja --no-progress -y
script:
  - mkdir build
  - cd build
  - cmake -G"$GENERATOR" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR ..
  - cmake --build . --config Release
  - ctest --output-on-failure -C Release
  - cmake --build . --config Release --target install
  - test -e $TRAVIS_BUILD_DIR/include/athr.h
  - test -e $TRAVIS_BUILD_DIR/lib/cmake/athr/athr-config.cmake
  - test -e $TRAVIS_BUILD_DIR/lib/cmake/athr/athr-targets-release.cmake
  - test -e $TRAVIS_BUILD_DIR/lib/cmake/athr/athr-targets.cmake
  - cd $TRAVIS_BUILD_DIR
  - git clean -xdf
before_deploy:
  - rm -rf figures
  - rm install*
notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
