language: c
jobs:
  include:
    - os: linux
      env: GENERATOR="Unix Makefiles"
    - os: osx
      env: GENERATOR="Unix Makefiles"
    - os: windows
      env: GENERATOR="Visual Studio 15 2017 Win64"
    - os: windows
      env: GENERATOR=Ninja
      before_install:
        - choco install ninja --no-progress -y
script:
  - mkdir build
  - cd build
  - cmake -G"$GENERATOR" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR
    ..
  - cmake --build . --config Release
  - ctest --output-on-failure -C Release
  - cmake --build . --config Release --target install
  - test -e $TRAVIS_BUILD_DIR/include/athr.h
  - test -e $TRAVIS_BUILD_DIR/lib/cmake/athr/athr-config.cmake
  - test -e $TRAVIS_BUILD_DIR/lib/cmake/athr/athr-targets-release.cmake
  - test -e $TRAVIS_BUILD_DIR/lib/cmake/athr/athr-targets.cmake
  - cd $TRAVIS_BUILD_DIR
before_deploy:
  - git clean -xdf
  - rm -rf figures
  - rm install*
notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: rW1Z2Ocu1pA6TnwMD93lCAwDkU4jfhL62hyL31+yEQrEHUFUg4pzxbr82oTBPMBS/e/mRcp+oZBt46GB2KqvCx3ebIhkSCZFx71tEHKRdl463njhdyQwOC3XKRORD0nnUs6HSm6iygaUnP4ZkO9YzfLbD3aDUXH4Sj/ihk4qH0kjVYHLvzzJefygn8Zoqe2at22bOmB6MFKc4xmrKMrpMOy8PkJX/Y5RogVyVfI6qn1SVx5XxDwzG5zUHHGjNxtby9AjNuK4aJxDJlYgRCN7zjbOnZ0qtHuOIjxxdW/WB3JkL6++AFus+kJRnAPTGU3mZDrCQBemE2dk9n3HcCAYu9ndHUCIwdLVvYS/uu4GrWKL7ME0DyqZIO2pubtU3X2reSLzbCAr/4Fdloxb6uQJilk2yODAZJRPOXRn2TO/oA96ivPwYshTSRBN3FE1u2huIJLj1f2at4KflwRO49OuhGyifzzfef98QnpXRqz6wph2UW5QMdCNQ5wpvEywqkXXd3QUc9YUg14L+pl9InwGwqK3iW+464uv9IBpSiZumY/O+8xZitSgTLxaeSC9afrEk8NXW8TlQwilu31WsHhaJlyFVgra0YBF/X2YcYWL3iiVbQewDSS20QovPxoFWvmLOoEnWhOaVTIt5zt6i++fqJUdwyofUQt/yUSnj6SkTRk=
  on:
    tags: true
    repo: horta/almosthere
    branch: master
    skip_existing: true
