os:
- linux
- osx
dist: trusty
sudo: false
language: c
compiler:
- clang
- gcc
script:
- mkdir build && pushd build
- cmake .. -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR -DCMAKE_BUILD_TYPE=Release
- make && make test && make install
- popd && rm -rf build
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -e $TRAVIS_BUILD_DIR/include/athr.h;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -e $TRAVIS_BUILD_DIR/lib/libathr.so;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -e $TRAVIS_BUILD_DIR/lib/libathr_static.a;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -e $TRAVIS_BUILD_DIR/include/athr.h;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -e $TRAVIS_BUILD_DIR/lib/libathr.dylib;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -e $TRAVIS_BUILD_DIR/lib/libathr_static.a;
  fi
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/almosthere/master/install)
after_success:
- mkdir dist && pushd dist && cmake .. -DCMAKE_BUILD_TYPE=Release && popd
- mv dist athr-`cat VERSION`
- tar czf athr-`cat VERSION`.tar.gz athr-`cat VERSION`
- rm -rf dist
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: okLPMGEkUGKgNKtfQLVc9qjm1u1tV2LAOimTkX3NScX6aANUQDxlxMeNnqRvfi+pFVfRddCWgOPR7OHJOx+3xdBNR+zWo7NWtYY3grevRFWczwl+U/GTiB+64U6bUxKlTb3P3d6a1eSGGPMMPXef5LutLIfsy/4QSWDWyXQp/iH94r1KmaW2b1sovrhq9J+/2XYfYnH52UFAifcODU+K1sFqlKLzK8Jth95IMPeuTWed28v7VbBkuyOtwqIDtkuEx6qGtwNqtVZFBn12lfBtRC06vRHjYZa8//BezJxC1Ewahq/y+rNnWHjyv/JLI55zTtPRo5svCIuALasxB3qs5yAWRxCdap+j0M0L0oZJsNmlWcsKWPnMEYFlJtH/Qd+wq75u2zfkMJWKCL3Kby2QZjTiT5On0U1hN8S/mFc9JqAEwbooX1YKMjNHvOxwDf9gXd0sBetPsdNJ5whZA6IVmMZsPELa0FJU+AjRAOXdfUWSMYMDct4B/F0c3CSg6UjklpkqeGZBVbXIfwtnO010h9f2f6K+7D7EzL/95+xcEm+fpe2iDM5g/UjtgkKs/+OIrXWgrJ0i8NLjOH/Jr2jzX3WcM4I3aUOzfR86n07OOIQQ512SQbLwRBEoNhjCb5NeLvf1pN0KqCBGHiHHemnXKRqkwnout5KWX+3yJxTOacg=
  on:
    repo: horta/almosthere
    tags: true
    branch: master
