environment:
    matrix:
      - PRJ_GEN: "Visual Studio 9 2008 Win64"
        BDIR: msvc2008
      - PRJ_GEN: "Visual Studio 10 2010 Win64"
        BDIR: msvc2010
      - PRJ_GEN: "Visual Studio 11 2012 Win64"
        BDIR: msvc2012
      - PRJ_GEN: "Visual Studio 12 2013 Win64"
        BDIR: msvc2013
      - PRJ_GEN: "Visual Studio 14 2015 Win64"
        BDIR: msvc2015
      - PRJ_GEN: "Visual Studio 15 2017 Win64"
        BDIR: msvc2017

build_script:
    - mkdir build.%BDIR%
    - cd build.%BDIR%
    - cmake .. -G"%PRJ_GEN%"
    - cmake --build . --config %PRJ_CFG% --clean-first
