#!/bin/bash

URL=https://raw.githubusercontent.com/horta/almosthere/master/VERSION
VERSION=$(curl -s $URL)

echo "[_/_] Library(athr==$VERSION)"

rm /tmp/athr.XXXX.log >/dev/null 2>&1 || true

logfile=$(mktemp /tmp/athr.XXXX.log)
exec 3>"$logfile"

function silent_run
{
    eval "$@ >&3 2>&1"
}

function silent_trun
{
    eval "$@ >&3 2>&1 || true"
}

function do_then_sudo
{
    eval "$@"
    if [ $? != 0 ]; then
        eval "sudo $@"
    fi
}

function failed
{
    echo "FAILED."
    echo "[_/_] LOG OUTPUT:"
    cat $logfile
    exit 1
}

FILE=athr-$VERSION.tar.gz
DIR=almosthere-$VERSION
URL=https://github.com/horta/almosthere/archive/$VERSION.tar.gz

silent_trun rm $FILE
silent_trun rm -rf $DIR

echo -n "[1/5] Downloading... "
silent_run curl -o $FILE -L $URL
[ $? == 0 ] && echo "done." || failed

tar xzf $FILE && cd $DIR
mkdir build && cd build

echo -n "[2/5] Configuring... "
silent_run cmake .. -DCMAKE_BUILD_TYPE=Release
[ $? == 0 ] && echo "done." || failed

echo -n "[3/5] Compiling... "
silent_run make
[ $? == 0 ] && echo "done." || failed

echo -n "[4/5] Testing... "
silent_run make test
[ $? == 0 ] && echo "done." || failed

echo -n "[5/5] Installing... "
silent_run do_then_sudo make install
[ $? == 0 ] && echo "done." || failed

cd .. && cd ..
silent_trun rm $FILE
silent_trun rm -rf $DIR

if type "ldconfig" >/dev/null 2>&1; then
    silent_run do_then_sudo ldconfig
fi

rm "$logfile" || true
