name: Test

on: push

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-13, macos-14, macos-15, windows-2022]

    steps:
      - uses: actions/checkout@v4
      - name: make
        run: make
      - name: make check
        run: make check
